"""
Django settings for billing_center project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import logging
import sys
ROOT_PATH = os.path.dirname(os.path.abspath(__file__))

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = '4e9hkv3b0&&axaz9v!(q822o&!=h82+)ki4amevdp-i7ad51!0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG=DEBUG

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'billing_center.center',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'center.generate_handle.Session_Timeout',
    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
#    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(ROOT_PATH, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "billing_center.settings.extern_context",
            ],
        },
    },
]

TEMPLATE_DIRS = (
    os.path.join(ROOT_PATH, 'templates'),
)

WSGI_APPLICATION = 'billing_center.wsgi.application'

try:
    sys.path.append("xxx")
    from settings_billing_center import *
    ImportFromEtcSuccess=True
except ImportError:
    ImportFromEtcSuccess=False
    logging.warning("Error import local_settings from xxx")

try:
    if not ImportFromEtcSuccess:
        from local.settings_billing_center import *
except ImportError:
    logging.warning("No local_settings file found.")


def extern_context(request):
    """
    Add some generally useful metadata to the template context
    """
    return {"root_url":BASE_URL,'tz':TIME_ZONE,'help_url':HORIZON_HELP_URL,'wo_url':HORIZON_WO_URL}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = TIME_ZONE

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
#STATIC_ROOT = os.path.abspath(os.path.join(ROOT_PATH, '.', 'static'))
STATIC_URL = '/static/'
STATICFILES_DIRS = (
            ROOT_PATH+ '/static',
            )
